Storyboard/Models/InterestViewModel.cs
using TeamProject.Data.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace TeamProject.Models
{
    public class InterestViewModel
    {  
        public List<Interest> Interests { get; set; }
        public int InterestId { get; set; }
        public string InterestCategory { get; set; }
    }

    public class InterestPostViewModel
    {
        [Required]
        public int InterestId { get; set; }
        public string InterestCategory { get; set; }
    }
}

Storyboard/Controllers/InterestController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TeamProject.Data;
using TeamProject.Data.Entities;
using TeamProject.Models;

namespace TeamProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class InterestController : Controller
    {
        private readonly IDataRepository _dataRepository;
        private readonly UserManager<User> _userManager;
        private readonly ILogger<InterestController> _logger;

        public InterestController(IDataRepository dataRepository,
            UserManager<User> userManager,
            ILogger<InterestController> logger)
        {
            _dataRepository = dataRepository;
            _userManager = userManager;
            _logger = logger;
        }


        public IActionResult Manage()
        {
            InterestViewModel interestData = new InterestViewModel
            {
                Interests = _dataRepository.GetAllInterests().ToList()
            };
            _logger.LogInformation("Admin navigated to Interest Management Page");
            return View(interestData);
        }

        [HttpPost]
        public IActionResult Create([FromBody]string newInterest)
        {
            var theNewInterest = new Interest
            {
                InterestCategory = newInterest
            };

            _dataRepository.AddEntity(theNewInterest);
            if (_dataRepository.SaveAll())
            {
                _logger.LogInformation("Ok new interest was created and saved to database");
            }
            return Ok("Interest Created");
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromBody]InterestPostViewModel interestData)
        {
            var thisUser = await _userManager.GetUserAsync(HttpContext.User);

            Interest toEdit = _dataRepository.GetInterestById(interestData.InterestId);
            toEdit.InterestCategory = interestData.InterestCategory;

            if (_dataRepository.SaveAll())
            {
                _logger.LogInformation("Interest with id: " + toEdit.InterestID + " successfully changed to " + toEdit.InterestCategory);
            }
            return Ok("Interest Edited");
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromBody]int id)
        {
            var thisUser = await _userManager.GetUserAsync(HttpContext.User);

            var toDelete = _dataRepository.GetInterestById(id);

            _dataRepository.DeleteEntity(toDelete);

            if (_dataRepository.SaveAll())
            {
                _logger.LogInformation("Deletion of interest was Successful");
            }
            return Ok("Interest Deleted");
        }
    }
}

Storyboard/Views/Interest/Manage.cshtml
@model InterestViewModel
@{
	ViewData["Title"] = "Manage Interests";
}
<div class="modal fade" id="createInterest" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Interests</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form asp-controller="Interest" asp-action="Create" asp-method="post">
					<div class="form-group">
						<label asp-for="@Model.InterestCategory" class="col-form-label">They are never enough</label>
						<input asp-for="@Model.InterestCategory" id="newInterestCategory" type="text" class="form-control">
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button id="Create" type="button" class="btn btn-primary" onclick="createInterest()">Create</button>
			</div>
		</div>
	</div>
</div>

<partial name="_DeleteThisPartial" />
<partial name="_EditCommentPartial" />

<div class="jumbotron jumbotron-fluid">
	<div class="container">
		<h1 class="display-3">&nbsp;<i class="fas fa-dice"></i> Manage Interests</h1>
	</div>
</div>

<button type="button" class="btn btn-lg btn-outline-light btn-block responsive-width mx-auto" style="background-color:#25a08d;" data-toggle="modal" data-target="#createInterest">Create a new Interest</button>
<br />
<div>
	<ul class="list-group responsive-width mx-auto">
		@foreach (Interest interest in Model.Interests)
		{
			<li class="list-group-item">
				<strong>@interest.InterestCategory</strong>

				<button class="btn btn-outline-danger float-right" onclick="deleteModal('@interest.InterestID')">Delete</button>
				<button class="btn btn-outline-info float-right" onclick="editModal('@interest.InterestID', '@interest.InterestCategory')">Edit</button>
			</li>
		}
	</ul>
</div>

<script>
	async function createInterest() {
		const url = "https://" + window.location.host + "@Url.Action("Create", "Interest")";
		const newInterest = document.getElementById("newInterestCategory").value;
		if ($.trim(newInterest) == '') {
			alert("An Interest Category cannot be empty!");
			return false;
		}
		await sendData(url, newInterest);
		location.reload();
	}
	let interestIDToChange;
	function editModal(id, previousText) {
		//Show the Modal
		$("#editThis").modal("show");
		$("#editText").attr("placeholder", previousText);
		interestIDToChange = id;
        $("#confirmChanges").click(async function ()
        {
			const newCategoryName = document.getElementById("editText").value;

            const url = "https://" + window.location.host + "@Url.Action("Edit", "Interest")";

            const data = {
				interestId: interestIDToChange,
                interestCategory: newCategoryName
            };
            console.log(data);
            await sendData(url, data);

            location.reload();
        });
    }

	function deleteModal(id){
		// Show the Modal
		$("#deleteThis").modal("show");

		$("#confirm-delete").click(async function ()
		{
			const url = "https://" + window.location.host + "@Url.Action("Delete", "Interest")";

			await sendData(url, id);

			location.reload();
		});
	}

	document.getElementById('newInterestCategory').addEventListener('keydown', (e) => {
		if (e.keyCode == 13) {
			e.preventDefault();
			createInterest();
			return false;
		}
	});
</script>