Storyboard/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TeamProject.Data;
using TeamProject.Data.Entities;
using TeamProject.Models;


namespace TeamProject.Controllers
{
    [Authorize]
    public class FriendController : Controller
    {
        private readonly IDataRepository dataRepository;
        private readonly UserManager<User> userManager;
        private readonly ILogger<FriendController> logger;

        public FriendController(IDataRepository dataRepository,
            UserManager<User> userManager,
            IHostingEnvironment env,
            ILogger<FriendController> logger)
        {
            this.dataRepository = dataRepository;
            this.userManager = userManager;
            this.logger = logger;
        }

        public async Task<IActionResult> Find()
        {
            User thisUser = await userManager.GetUserAsync(HttpContext.User);
            var allAvailableFriends = dataRepository.GetAllStrangeUsers(await userManager.GetUserAsync(HttpContext.User));
            List<UserModel> ToBeFriends = new List<UserModel>();
            foreach (User availableFriend in allAvailableFriends)
            {
                UserModel toBeFriend = new UserModel
                {
                    Id = availableFriend.Id,
                    Avatar = availableFriend.UserAvatar,
                    UserName = availableFriend.UserName,
                    Name = availableFriend.FirstName + " " + availableFriend.LastName,
                    FriendshipStatus = dataRepository.GetFriendship(thisUser, availableFriend),
                    TopInterests = dataRepository.GetTopUsersInterests(availableFriend)
                };
                ToBeFriends.Add(toBeFriend);
            }
            FriendViewModel data = new FriendViewModel
            {
                ThisUser = thisUser,
                SentRequests = ToBeFriends.Where(u => u.FriendshipStatus == Friendship.removeRequest).ToList(),
                ReceivedRequests = ToBeFriends.Where(u => u.FriendshipStatus == Friendship.acceptRequest).ToList(),
                OtherUsers = ToBeFriends.Where(u => u.FriendshipStatus == Friendship.addFriend).ToList()
            };
            logger.LogInformation("User " + thisUser.UserName + " navigated to Find Friends Page");

            return View(data);
        }


        [Route("/makefriend/{userid}")]
        [HttpGet("{userid}")]
        public async Task<IActionResult> Make(string userid)
        {
            User theNewFriend = await userManager.FindByIdAsync(userid);
            User thisUser = await userManager.GetUserAsync(HttpContext.User);

            if (theNewFriend is null || thisUser is null) throw new Exception();

            Friend newFriendship = new Friend
            {
                Receiver = theNewFriend,
                Sender = thisUser,
                Accept = false
            };

            dataRepository.AddEntity(newFriendship);
            if (dataRepository.SaveAll())
            {
                logger.LogInformation("Ok a new friend request was created");
            };
            return RedirectToAction("Personal", "Home", new { username = theNewFriend.UserName });
        }

        [Route("/addfriend/{userid}")]
        [HttpGet("{userid}")]
        public async Task<IActionResult> Accept(string userid)
        {
            User thisUser = await userManager.GetUserAsync(HttpContext.User);
            User theNewFriend = await userManager.FindByIdAsync(userid);

            if (userid is null || thisUser is null) throw new Exception();

            Friend friendship = dataRepository.GetFriend(thisUser, userid);
            friendship.Accept = true;
            if (dataRepository.SaveAll())
            {
                logger.LogInformation("Ok a new friendship was created");
            };
            return RedirectToAction("Personal", "Home", new { username = theNewFriend.UserName });
        }

        [Route("/unfriend/{userid}")]
        [HttpGet("{userid}")]
        public async Task<IActionResult> Remove(string userid)
        {
            User thisUser = await userManager.GetUserAsync(HttpContext.User);
            User theNewFriend = await userManager.FindByIdAsync(userid);

            if (userid is null || thisUser is null) throw new Exception();

            Friend friendship = dataRepository.GetFriend(thisUser, userid);

            dataRepository.DeleteEntity(friendship);
            if (dataRepository.SaveAll())
            {
                logger.LogInformation("Ok a friendship was broken successfully");
            };
            return RedirectToAction("Personal", "Home", new { username = theNewFriend.UserName });
        }
    }
}

Storyboard/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TeamProject.Data;
using TeamProject.Data.Entities;
using TeamProject.Models;

namespace TeamProject.Controllers
{
    [Authorize]
    public class PostController : Controller
    {

        private readonly IDataRepository _dataRepository;
        private readonly UserManager<User> _userManager;
        private readonly IHostingEnvironment _env;
        private readonly ILogger<PostController> _logger;

        public PostController(IDataRepository dataRepository,
            UserManager<User> userManager,
            IHostingEnvironment env,
            ILogger<PostController> logger)
        {
            _dataRepository = dataRepository;
            _userManager = userManager;
            _env = env;
            _logger = logger;
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm]CreatePostViewModel newPostData)
        {
            var thisUser = await _userManager.GetUserAsync(HttpContext.User);

            if (ModelState.IsValid)
            {
                List<Interest> addedInterests = new List<Interest>();
                if (!(newPostData.Interests[0] is null))
                {
                    List<Interest> interests = (List<Interest>)_dataRepository.GetAllInterests();
                    foreach (Interest interest in interests)
                    {
                        if (newPostData.Interests[0].Contains(interest.InterestCategory))
                        {
                            addedInterests.Add(interest);
                        }
                    }
                }

                DateTime timeStamp = DateTime.Now;
                Post theNewPost = new Post
                {
                    User = thisUser,
                    PostDate = timeStamp,
                    PostText = newPostData.PostText,
                    PostScope = (Scope)newPostData.PostScope
                };

                _dataRepository.AddEntity(theNewPost);

                if (_dataRepository.SaveAll())
                {
                    _logger.LogError("Ok new post was saved");
                };
                Post savedPost = _dataRepository.GetPostByTimeStamp(timeStamp);

                var image = newPostData.PostImage;
                if (image != null && image.Length > 0)
                {
                    if (image.ContentType.Contains("png") || image.ContentType.Contains("jpg") || image.ContentType.Contains("jpeg"))
                    {
                        var filePath = _env.WebRootPath + "\\postImages\\" + savedPost.PostID + '.' + image.ContentType.Split('/')[1];

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await image.CopyToAsync(stream);
                        }
                        savedPost.PostImage = "/postImages/" + savedPost.PostID + '.' + image.ContentType.Split('/')[1];
                    }
                }

                foreach (Interest interest in addedInterests)
                {
                    PostInterest postInterest = new PostInterest
                    {
                        Interest = interest,
                        Post = savedPost
                    };
                    _dataRepository.AddEntity(postInterest);
                }
                if (_dataRepository.SaveAll())
                {
                    _logger.LogError("Ok relationship of post and interests was saved");
                };
                return Ok("Ok new post was saved");
            }
            return BadRequest("Something was missing");

        }

        [HttpPost]
        public async Task<IActionResult> AddReaction([FromBody]ReactionModel reactionData)
        {
            var thisUser = await _userManager.GetUserAsync(HttpContext.User);
            Post reactedPost;
            if (ModelState.IsValid)
            {

                Reaction postReaction = _dataRepository.GetReactionByPostAndUser(reactionData.PostId, thisUser);

                // Does the reaction already exist?
                if (postReaction is null)
                {
                    reactedPost = _dataRepository.GetPostById(reactionData.PostId);
                    postReaction = new Reaction
                    {
                        Post = reactedPost,
                        User = thisUser,
                        IsLike = reactionData.IsLike
                    };

                    _dataRepository.AddEntity(postReaction);

                    if (_dataRepository.SaveAll())
                    {
                        _logger.LogInformation("NEW Reaction Saved to Database");
                    };
                }
                else
                {
                    if (postReaction.IsLike != reactionData.IsLike)
                    {
                        postReaction.IsLike = reactionData.IsLike;
                        if (_dataRepository.SaveAll())
                        {
                            _logger.LogInformation("Reaction was changed and Saved to Database");
                        };
                    }
                }
            }
            reactedPost = _dataRepository.GetPostById(reactionData.PostId);

            // Return the new amount of likes and dislikes
            return Json(new
            {
                likes = reactedPost.Reactions.Where(r => r.IsLike).ToList().Count,
                dislikes = reactedPost.Reactions.Where(r => !r.IsLike).ToList().Count
            });
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromBody]int id)
        {
            var thisUser = await _userManager.GetUserAsync(HttpContext.User);

            Post toDelete = _dataRepository.GetPostById(id);

            if (_dataRepository.DeletePost(toDelete))
            {
                _logger.LogInformation("The post was deleted successfully");
            }
            return Ok("Post Deleted");
        }
    }
}

Storyboard/Controllers/UploadController.cs
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TeamProject.Data.Entities;

namespace TeamProject.Controllers
{
    [Authorize]
    public class UploadController : Controller
    {
        private readonly IHostingEnvironment _env;
        private readonly UserManager<User> _userManager;

        public UploadController(IHostingEnvironment env,
            UserManager<User> userManager)
        {
            _env = env;
            _userManager = userManager;
        }
        
        [HttpPost]
        public async Task UserAvatar(IFormFile image)
        {
            // full path to file in temp location
            if (image is { Length: > 0 })
            {
                if (image.ContentType.Contains("png") || image.ContentType.Contains("jpg") || image.ContentType.Contains("jpeg"))
                {
                    var userId = _userManager.GetUserId(HttpContext.User);
                    var filePath = _env.WebRootPath + "\\userAvatars\\" + userId + '.' + image.ContentType.Split('/')[1];

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                    var user = await _userManager.GetUserAsync(User);
                    user.UserAvatar = "/userAvatars/" + userId + '.' + image.ContentType.Split('/')[1];
                    var updateProfileResult = await _userManager.UpdateAsync(user);
                }
            }
            // process uploaded files
            // Don't rely on or trust the FileName property without validation.
            Response.Redirect("/Identity/Account/Manage");
        }

    }
}

Storyboard/Controllers/UsersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TeamProject.Data;
using TeamProject.Data.Entities;
using TeamProject.Models;

namespace TeamProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IDataRepository _dataRepository;
        private readonly UserManager<User> _userManager;
        private readonly ILogger<UsersController> _logger;

        public UsersController(IDataRepository dataRepository,
            UserManager<User> userManager,
            ILogger<UsersController> logger)
        {
            _dataRepository = dataRepository;
            _userManager = userManager;
            _logger = logger;
        }

        [Route("/manageusers")]
        public async Task<IActionResult> Manage()
        {
            var thisUser = await _userManager.GetUserAsync(HttpContext.User);
            var allUsers = _dataRepository.GetAllUsersExcept(thisUser);

            var admins = await _userManager.GetUsersInRoleAsync("Admin");

            var accessUsers = allUsers.Select(assessUser =>
                    new UserManagementModel
                    {
                        Id = assessUser.Id,
                        Avatar = assessUser.UserAvatar,
                        UserName = assessUser.UserName,
                        Name = assessUser.FirstName + " " + assessUser.LastName,
                        IsAdmin = admins.Select(u => u.Id).Contains(assessUser.Id)
                    })
                .ToList();

            _logger.LogInformation("Admin {Name} navigated to manage users Page", thisUser.UserName);
            return View(accessUsers);
        }

        [HttpPost]
        public async Task<IActionResult> MakeAdministrator([FromBody] string userid)
        {
            if (userid is null) throw new Exception();
            var upToAdmin = await _userManager.FindByIdAsync(userid);

            await _userManager.AddToRoleAsync(upToAdmin, "Admin");
            if (_dataRepository.SaveAll())
            {
                _logger.LogInformation("Ok the user was promoted");
            }

            return Ok("User Promoted");
        }

        [HttpPost]
        public async Task<IActionResult> MakeUser([FromBody] string userid)
        {
            if (userid is null) throw new Exception();
            var backToUser = await _userManager.FindByIdAsync(userid);

            await _userManager.RemoveFromRoleAsync(backToUser, "Admin");
            if (_dataRepository.SaveAll())
            {
                _logger.LogInformation("Ok the admin was downgraded");
            }

            return Ok("Admin no more");
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromBody] string userid)
        {
            var toBeDeleted = await _userManager.FindByIdAsync(userid);

            if (userid is null) throw new Exception();

            _dataRepository.DeleteUser(toBeDeleted);
            if (_dataRepository.SaveAll())
            {
                _logger.LogInformation("Ok the user was deleted");
            }
            return Ok("User Deleted");
        }
    }
}

Storyboard/Views/Shared/_CreatePostPartial.cshtml
@model MyWallViewModel
<button type="button" class="btn btn-lg btn-outline-light btn-block responsive-width mx-auto" style="background-color:#25a08d;" data-toggle="modal" data-target="#createPost">Create a new Post</button>
<br />
<div class="modal fade" id="createPost" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content" id="modalContent">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">What's in your mind?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form>
					<select name="scope" id="scope" onchange="changeScope(this)">
						<option value=0 selected>Global</option>
						<option value=1>Personal</option>
					</select>
					<p id="interests-off-post">
						@foreach (Interest interest in Model.Interests)
						{
							<span class="badge badge-secondary" onclick="toggleInterest(this)">@interest.InterestCategory</span>
						}
					</p>
					<p id="interests-in-post"></p>
					<div class="form-group">
						<input id="postText" type="text" class="form-control" placeholder="Say something..">
						<label for="postImage" class="col-form-label">Add an image..</label>
						<input id="postImage" type="file" class="form-control" name="image">
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="button" id="createNewPostButton" class="btn btn-primary" onclick="sendNewPost()">Save Post</button>
			</div>
		</div>
	</div>
</div>

<script>
	let interests = [];
	let scope = 0;

	function toggleInterest(element) {
		const offInterests = document.getElementById("interests-off-post");
		const inInterests = document.getElementById("interests-in-post");
		const index = interests.findIndex(x => x === element.innerHTML);
		if (index >= 0) {
			element.setAttribute("class", "badge badge-secondary");
			inInterests.removeChild(element);
			offInterests.appendChild(element);
			interests.splice(index, 1);
		}
		else {
			element.setAttribute("class", "badge badge-primary");
			offInterests.removeChild(element);
			inInterests.appendChild(element);
			interests.push(element.innerHTML);
		}
	}

	function changeScope(element)
	{
		scope = element.value;
	}

	async function sendNewPost()
	{
		const newPostText = document.getElementById("postText").value;

		if ($.trim(newPostText) == '') {
			return false;
		}

		let input = document.querySelector('input[type="file"]')

		let data = new FormData()
		data.append('PostImage', input.files[0])
		data.append('PostText', newPostText)
		data.append('PostScope', scope)
		data.append('Interests', interests)

        const urlToSendRequest = "https://" + window.location.host + "@Url.Action("Create", "Post")";

        // Add loader until post is saved to database
        const loader = document.createElement("img");
        loader.setAttribute("src", "/images/loader.svg");
        const modalContent = document.getElementById('modalContent');
        modalContent.innerHTML = '';
        modalContent.appendChild(loader);

		const rawData = await fetch(urlToSendRequest,
		{
			method: 'POST',
			credentials: "same-origin",
			body: data
		});

		location.reload();
	}
	document.getElementById('postText').addEventListener('keydown', (e) => {
		if (e.keyCode == 13) {
			e.preventDefault();
			sendNewPost();
			return false;
		}
	});
</script>

Storyboard/Views/Shared/_DeleteThisPartial.cshtml
<div class="modal fade" id="deleteThis" tabindex="-1" role="dialog" aria-labelledby="deleteThisLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Are you sure, you want to delete that?</h5>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
				<button type="button" class="btn btn-danger" id="confirm-delete">Yes</button>
			</div>
		</div>
	</div>
</div>

Storyboard/Views/Shared/_EditCommentPartial.cshtml
<div class="modal fade" id="editThis" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">We all make mistakes</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form>
					<div class="form-group">
						<label for="editText" class="col-form-label">That's what makes us human.. Now fix it</label>
						<input id="editText" type="text" class="form-control">
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button id="confirmChanges" type="button" class="btn btn-primary">Save Changes</button>
			</div>
		</div>
	</div>
</div>
<script>
	document.getElementById('editText').addEventListener('keydown', (e) => {
		if (e.keyCode == 13) {
			e.preventDefault();
			document.getElementById('confirmChanges').click();
			return false;
		}
	});
</script>

Storyboard/Views/Shared/_ImageUploadPartial.cshtml
<div class="modal fade" id="uploadImage" tabindex="-1" role="dialog" aria-labelledby="uploadForm" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="uploadForm">Upload an image</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form asp-controller="Upload" asp-action="UserAvatar" method="post" enctype="multipart/form-data">
				<div class="modal-body">
					<div class="form-group">
						<label for="instructions" class="col-form-label">Images can be of type PNG or JPG</label>
						<input id="image" type="file" class="form-control" name="image">
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Upload</button>
				</div>
			</form>
		</div>
	</div>
</div>

Storyboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Bits Please</title>
	<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

	<style media="screen" type="text/css">
		.navbar-brand {
			padding: 0px;
		}

			.navbar-brand > img {
				height: 100%;
				/*padding: 8px;*/
				width: auto;
			}
	</style>
</head>
<body>
	<nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: #446789;">
		<div class="container">
			<div class="navbar-brand">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<a asp-area="" asp-controller="Home" asp-action="Index" asp-route-id="" class="navbar-brand">
					<img src="~/images/Logo.png" />
				</a>
			</div>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" id="nav-link-personal" asp-area="" asp-controller="Home" asp-action="Personal" asp-route-username="">
							<i class="fas fa-user-astronaut">&nbsp;</i> Profile
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="nav-link-find" asp-area="" asp-controller="Friend" asp-action="Find">
							<i class="fas fa-users">&nbsp;</i> Find Friends
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="nav-link-messenger" asp-area="" asp-controller="Messenger" asp-action="Chat">
							<i class="far fa-envelope">&nbsp;</i> Messenger
						</a>
					</li>
					@if (User.Identity.IsAuthenticated)
					{
						@if (User.IsInRole("Admin"))
						{
							<li class="nav-item">
								<a class="nav-link" id="nav-link-interest" asp-area="" asp-controller="Interest" asp-action="Manage">
									<i class="fas fa-dice">&nbsp;</i> Interests
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" id="nav-link-interest" asp-area="" asp-controller="Users" asp-action="Manage">
									<i class="fas fa-building">&nbsp;</i> Users
								</a>
							</li>
						}
					}
				</ul>
				<partial name="_LoginPartial" />
			</div>
		</div>
	</nav>

	<partial name="_CookieConsentPartial" />

	<div class="container body-content">
		@RenderBody()
	</div>
	<footer>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="container">
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
						</li>
						<li class="nav-item">
							<p class="navbar-text">&copy; 2018 - BitsPlease</p>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</footer>
	<script src="~/lib/moment/moment.min.js"></script>
	<script src="~/lib/moment/moment-with-locales.js"></script>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/linkify/linkify.js"></script>
        <script src="~/lib/linkify/linkify-html.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

    </environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
		</script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>